### ISSUE TITLE
Need option to set client or request timeout

### ISSUE THREAD

**Issue by ohaag** [Zeichen32/GitLabApiBundle#24]
Hello,
It would be nice to have a way to define the client timeout in the bundle configuration.
For requests timeout, you could add an optional parameters letting us set request headers.

Be able to customize the whole client timeout would probably be enough though.

**Comment by Zeichen32** [comment]
By default the bundle should use the symfony http client, which you can configure in you framework.yaml to set a custom timeout.
https://symfony.com/doc/current/http_client.html#configuration

You can also create a new symfony http client with your options and use the http_client option in the bundle config.

```yaml
zeichen32_git_lab_api:
    clients:              # Required
        token:                ~ # Required
        url:                  ~ # Required
        auth_method:          ~ http_token|oauth_token
        sudo:                 ~
        alias:                ~
        http_client:          ~ # http client service id
```
